name: gridtest1
favicon: null
layout_spectrum: 0.5670662492047995
typography_spectrum: 0.31049450882710516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.21570372488349676
  lightness: 0.12473752512596548
  saturation: 0.8572689373977482
  rhythmicContrast: 0.3244349507149309
purpose: []
